name: 'ecs task definition replacements'
description: 'get the currently running task definition, replace values (like image)'
inputs:
  cluster-name:  # id of input
    description: cluster that service is running
    required: true
  service-name:  # id of input
    description: service to get current running task definition
    required: false
  task-name:  # id of input
    description: task family to get the latest task definition revision
    required: false
  replacements:  # id of input
    description: "JSON between '' eg '{\"name\": \"Andrew\"}'"
    required: true

outputs:
  taskDef:
    description: 'Path to the new json file'
runs:
  using: 'node12'
  main: 'dist/index.js'
